config/routes.rb
Rails.application.routes.draw do
  get 'users/update'

  resources :commits, only: %i(index create)
  resources :users,   only: %i(update)
  root to: 'commits#index'
end

app/models/commit.rb
# == Schema Information
#
# Table name: commits
#
#  id          :integer          not null, primary key
#  commited_at :datetime
#  user_id     :integer          indexed
#  sha         :string
#  message     :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_commits_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_409a66d7e3  (user_id => users.id)
#

class Commit < ActiveRecord::Base
  extend Truncatable
  belongs_to :user

  scope :for_user, ->(email) { joins(:user).merge(User.by_email(email)) }

end

app/models/concerns/truncatable.rb
module Truncatable
  def truncate
    destroy_all # Only necessary if you want to trigger callbacks.
    ActiveRecord::Base.connection.execute("TRUNCATE #{table_name} CASCADE")
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string           indexed
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email)
#

class User < ActiveRecord::Base
  extend Truncatable

  scope :by_email, ->(email) { where("email LIKE ?", email) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/commits_controller.rb
# == Schema Information
#
# Table name: commits
#
#  id          :integer          not null, primary key
#  commited_at :datetime
#  user_id     :integer          indexed
#  sha         :string
#  message     :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_commits_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_409a66d7e3  (user_id => users.id)
#

class CommitsController < ApplicationController
  def index
    @commits = Commit.includes(:user)
    if params[:email]
      @commits = @commits.for_user params[:email]
    end
    @commits = @commits.page(params[:page])
  end

  def create
    if ImportService.run(import_params[:user], import_params[:repo]).present?
      redirect_to({ action: :index }, notice: 'Imported'  )
    else
      redirect_to({ action: :index }, alert: 'Import error' )
    end

  end

  private
  def import_params
    @import_params ||= params.require(:import).permit(:user, :repo)
  end
end

app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string           indexed
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email)
#

class UsersController < ApplicationController
  def update
    @user = User.find(params[:id])
    attrs = {}
    attrs[params[:name]] = params[:value]
    @user.update_attributes(attrs)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commits_helper.rb
module CommitsHelper
end

app/views/commits/_commit.html.haml
%tr
  %td.sha
    %span.label.label-info= commit.sha
  %td.message= commit.message
  %td.commited= l commit.commited_at, format: :short
  %td.user
    %a.editable{ href: '#', data: { type: 'text', pk: commit.user.id, url: user_path(commit.user), name: 'name', title: 'Enter username' } }
      = commit.user.try(:name)

app/views/commits/_form.html.haml
.row
  .col-md-6
    = form_for :import, url: commits_path, html: { class: 'form-inline'} do |f|
      .form-group
        = f.text_field :user, placeholder: 'User', class: 'form-control'
      .form-group
        = f.text_field :repo, placeholder: 'Repo', class: 'form-control'
      .form-group
        = submit_tag 'Import', class: 'btn btn-primary'
  .col-md-6
    .pull-right
      = form_tag commits_path, method: 'get', enforce_utf8: false, class: 'form-inline' do
        .input-group
          = search_field_tag :email, '', placeholder: 'Email', class: 'form-control'
          .input-group-btn
            %button.btn.btn-default
              %i.glyphicon.glyphicon-search

app/views/commits/create.html.haml
%h1 Commits#create
%p Find me in app/views/commits/create.html.haml

app/views/commits/index.html.haml
.row
  .col-md-12
    .well
      = render 'form'

.row
  .col-md-12
    = paginate @commits, :theme => 'twitter-bootstrap-3'

.row
  .col-md-12
    %table.table
      %thead
        %th.sha= Commit.human_attribute_name('sha')
        %th.message= Commit.human_attribute_name('message')
        %th.commited= Commit.human_attribute_name('commited_at')
        %th.user= Commit.human_attribute_name('user')
      %tbody
        = render @commits

.row
  .col-md-12
    = paginate @commits, :theme => 'twitter-bootstrap-3'

app/views/layouts/_alerts.html.haml
#alerts
  - flash.each do |k, v|
    .alert{ role: 'alert', class: k == 'alert' ? 'alert-danger' : 'alert-success' }= v

app/views/layouts/_footer.html.haml
%footer
  %p &copy; 2016

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %a.navbar-brand{href: root_path} Commit viewer

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Commit viewer
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css', integrity: 'sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7', crossorigin: 'anonymous'

    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      = render 'layouts/alerts'
      = yield
      = render 'layouts/footer'

    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/users/update.js.erb
$('.user .editable[data-pk=<%= @user.id%>]').html("<%= @user.name %>")